### ISSUE TITLE
Bad mapping for some properties & incoherent default values

### ISSUE THREAD

**Issue by studiodev** [edulify/play-hikaricp.edulify.com#41] opened 2015-02-14 15:43 UTC
Hello,

I found that some DB properties are not retrieved with the right key in PlayConfig mode.

In play-hikari

    properties.setPropertyFromConfig("autoCommit",          "defaultAutoCommit", "true")
    properties.setPropertyFromConfig("transactionIsolation", "defaultTransactionIsolation")
    properties.setPropertyFromConfig("readOnly",             "defaultReadOnly", "false")

In play ([doc](https://www.playframework.com/documentation/2.3.x/SettingsJDBC )) ([source](https://github.com/playframework/playframework/blob/814f2cac35faeea0451b0ebc79b9a6e636ddaf1a/framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala#L124)) :

    conf.getBoolean("autocommit")
    conf.getString("isolation")
    conf.getBoolean("readOnly")

In addition, some default properties doesn't match with the Hikaricp or Play default values.
For example :

Property | Play default | Hikaricp default | Play-Hikaricp default
------------ | ------------- | -------------- | ----------
`maximumPoolSize` | 2*5 = 10 | 10 | 1*30 = 30
`minimumIdle` | 2*5 = 10 | 10 | 1*5 = 5

If it's an intended optimization, it should be explained in the Readme.

**Comment by megazord** [comment] 2015-02-15 17:24
It is not a intended optimization. This was probably caused by outdated defaults, since play and hikari was updated without reconsidering the new defaults.

**Comment by megazord** [comment] 2015-02-17 22:12
Closed in release 1.5.2

**Closed by megazord** 2015-02-17 22:12 UTC
Labels: enhancement

**Comment by studiodev** [comment] 2015-02-18 09:10
Thanks for the release :)
